### ISSUE TITLE
Doesn't work with Django 3.1

### ISSUE THREAD

**Issue by MxFlix** [EliotBerriot/django-dynamic-preferences#216]
When using Dynamic Preferences with Django 3.1, the error `ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields'` appears. Probably related to "The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed." as mentioned [here](https://docs.djangoproject.com/en/dev/releases/3.1/#id1)

**Comment by EliotBerriot** [comment]
Fixed in  e618b78, thank you for the report

**Comment by nuthingman** [comment]
Any change of releasing the fix to Pypi?
